language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: aeDZlCwbwrWUHVYn9nzGQPKzi6il3Xi49wubFOvStySUPoIZ2vn73uHeUewX9BQGbpnMloglPYh1B8oX8u0w+CWWtgP55e0FG6zbBhaFLxHWCQUB2JWvl0B0aP5ykNQeEGotYPxMuzoKjAiAdPFsFbWia3ri94je4qADfR14VdmvwnshIb1JujSlO28e133qsTWoB5bc6VpI6kd+2dkequBnUGCoLA7i2eTsaauz5rU664/w4PPtTUla9slt+IcvPtGuU3BaFJwKyi4x1c5jDMnLsqqXGbsGghoL1KZvMm5dtezSwdz8JWNlEdIyfPLMITz8kwmS38zAyeaZTTdADLS5se0cQ2NuNKpf7uRvRU3aXpbpJ2J88ND90VCv248wqb5/QCWJkbScWeP5ZiJEx7iZVCdQkNJjU9kZt1xIGgX5sD/59DstWzK003D69+4KZAIg1YWEci2QW1xMvvjYwv9/ZCsRKFmGGEAPPuI4XzPDyPlJUUNMcCvLXW62eusQ/9jnzXNUlbCWaZi4PmFxP4EmcGq+S+023S3b4LJWV+ZjP8Ezq5mRufuw8xBpSU+8sA8PIz09aU/4pM9BgxT5Oz6Rv34Kj3NUjwhyIkJTRZC9gNyLO00/z69HlJ5L5Avvclu3Sct822wFYaNyttxIvw+rDFn7uwDQLxvZ7LJM8Wg=
  file:
    - 'a-rel.js'
    - 'a-rel.min.js'
  on:
    tags: true
