language: node_js
node_js:
- lts/boron
- node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: jsL9/uiZxnmu8QZ7HozMGLjdhFLam971ZPjhMJ4Z4Wqg80MKiOn6505mNvsw9OVUaQUlaAaEiWQIwrcUicH+h2FRozxfeow7y+hrk+bgTYqJ4Ikz4DLFMvFNrI6CguCE5AiwFjqBe63W/Xk2Ubvz77gb00B5tHv/z3HIW2WyPg6kYrGmunYd2Nv+CwLp2zioSdoW5LdOnB/+yerHecNcTsIWK4AWCJjTU9k53fh4LE7yhsJh9N8mARmKwqIbW2IYOXTaB9jnXm8QDJIvK+n8V9CoPiwNcv3ynwPofPizbWzFz1q+CvNHDfrhr0njpew8dVvK0Y9AERqwHSMKq+Zn6nleTN/+0x+rJmGWbs/sccRDJSr4pOXe5JZCG1/dojTFfiRv0G+oepr5BYm2V8Mz7QywVvTRpLA+dZqllOt9hZn/MRm7unJ2waWdOSfrMN9E1WdXxQmYc1scpdhDStGfnmSZu+f4mpjmAn30aoeEyFl9TOI8V89sRB/+mXgq/rGOgFxeiIk4H+vg1db1U27FyDfo6u3BeeNbPDLO+UHmKk5qQoHmViQCRvCjRK86W0ix+pJAsT/0H3p8XhtTSdYJu0AmhYAn1v/WtZMe1JO9uoroHKALQT35DxnMsqkaGSi4fsrlyU9xQh0dGdCyKb0eA1QeBHsqJXTmpUmxX76cRmk=
  file:
    - "a-rel.js"
    - "a-rel.min.js"
  on:
    tags: true
